sudo: required
services:
    - docker

before_install:
    - docker build -t viswatejasunkara/docker-react -f Dockerfile.dev .

script:
    - docker run viswatejasunkara/docker-react npm run test -- --coverage